import {
  AdminOrder,
  AdminSeller,
  AdminRider,
  AdminCustomer,
  AdminProduct,
  AdminRefund,
  AdminSettlement,
  ServiceAreaZone,
  PricingConfig,
  AuditLogEntry,
  SupportTicket,
  IndianCityConfig,
  AdminPromotion,
  SponsoredAdCampaign,
  CmsHeroBanner,
  CmsCuratedCollection,
  AdminEmployeeUser,
  AdminRoleDefinition,
} from '../../src/types/admin';
import { DEFAULT_DYNAMIC_ROLES } from '../rbac';

class AdminStore {
  public cities: IndianCityConfig[] = [];
  public orders: AdminOrder[] = [];
  public sellers: AdminSeller[] = [];
  public riders: AdminRider[] = [];
  public customers: AdminCustomer[] = [];
  public products: AdminProduct[] = [];
  public refunds: AdminRefund[] = [];
  public settlements: AdminSettlement[] = [];
  public serviceAreas: ServiceAreaZone[] = [];
  public pricingConfig: PricingConfig;
  public auditLogs: AuditLogEntry[] = [];
  public supportTickets: SupportTicket[] = [];
  public promotions: AdminPromotion[] = [];
  public sponsoredAds: SponsoredAdCampaign[] = [];
  public cmsBanners: CmsHeroBanner[] = [];
  public cmsCollections: CmsCuratedCollection[] = [];
  public employees: AdminEmployeeUser[] = [];
  public dynamicRoles: AdminRoleDefinition[] = [];

  constructor() {
    this.pricingConfig = {
      freeDeliveryThreshold: 499,
      baseDeliveryFee: 25,
      platformFee: 5,
      urgencyHandlingFee: 15,
      defaultSellerCommissionPercent: 8.5,
      riderBasePay: 40,
      riderPerKmPay: 12,
      surgeActive: false,
      surgeMultiplier: 1.0,
    };

    this.dynamicRoles = [...DEFAULT_DYNAMIC_ROLES];
    this.seedInitialData();
  }

  private seedInitialData() {
    // 1. Pan-India Metropolitan & Tier-1 City Hubs
    this.cities = [
      {
        id: 'bengaluru',
        name: 'Bengaluru',
        state: 'Karnataka',
        region: 'South',
        stateGstPrefix: '29',
        status: 'ACTIVE',
        totalZones: 6,
        activeZones: 5,
        activePartnerStores: 14,
        activeRiders: 146,
        avgDeliverySlaMins: 14.8,
        defaultSurgeMultiplier: 1.0,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        minOrderValue: 199,
      },
      {
        id: 'mumbai',
        name: 'Mumbai & MMR',
        state: 'Maharashtra',
        region: 'West',
        stateGstPrefix: '27',
        status: 'ACTIVE',
        totalZones: 6,
        activeZones: 6,
        activePartnerStores: 18,
        activeRiders: 184,
        avgDeliverySlaMins: 13.9,
        defaultSurgeMultiplier: 1.15,
        baseDeliveryFee: 30,
        freeDeliveryThreshold: 599,
        minOrderValue: 249,
      },
      {
        id: 'delhi_ncr',
        name: 'Delhi NCR',
        state: 'Delhi / Haryana / UP',
        region: 'North',
        stateGstPrefix: '07',
        status: 'ACTIVE',
        totalZones: 6,
        activeZones: 5,
        activePartnerStores: 16,
        activeRiders: 162,
        avgDeliverySlaMins: 15.2,
        defaultSurgeMultiplier: 1.1,
        baseDeliveryFee: 29,
        freeDeliveryThreshold: 549,
        minOrderValue: 229,
      },
      {
        id: 'hyderabad',
        name: 'Hyderabad',
        state: 'Telangana',
        region: 'South',
        stateGstPrefix: '36',
        status: 'ACTIVE',
        totalZones: 5,
        activeZones: 5,
        activePartnerStores: 11,
        activeRiders: 98,
        avgDeliverySlaMins: 14.1,
        defaultSurgeMultiplier: 1.0,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        minOrderValue: 199,
      },
      {
        id: 'chennai',
        name: 'Chennai',
        state: 'Tamil Nadu',
        region: 'South',
        stateGstPrefix: '33',
        status: 'ACTIVE',
        totalZones: 5,
        activeZones: 4,
        activePartnerStores: 10,
        activeRiders: 84,
        avgDeliverySlaMins: 16.4,
        defaultSurgeMultiplier: 1.0,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        minOrderValue: 199,
      },
      {
        id: 'pune',
        name: 'Pune',
        state: 'Maharashtra',
        region: 'West',
        stateGstPrefix: '27',
        status: 'ACTIVE',
        totalZones: 4,
        activeZones: 4,
        activePartnerStores: 9,
        activeRiders: 76,
        avgDeliverySlaMins: 14.5,
        defaultSurgeMultiplier: 1.05,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        minOrderValue: 199,
      },
      {
        id: 'kolkata',
        name: 'Kolkata',
        state: 'West Bengal',
        region: 'East',
        stateGstPrefix: '19',
        status: 'ACTIVE',
        totalZones: 4,
        activeZones: 3,
        activePartnerStores: 7,
        activeRiders: 54,
        avgDeliverySlaMins: 17.2,
        defaultSurgeMultiplier: 1.0,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        minOrderValue: 199,
      },
      {
        id: 'ahmedabad',
        name: 'Ahmedabad',
        state: 'Gujarat',
        region: 'West',
        stateGstPrefix: '24',
        status: 'ACTIVE',
        totalZones: 4,
        activeZones: 4,
        activePartnerStores: 8,
        activeRiders: 62,
        avgDeliverySlaMins: 13.5,
        defaultSurgeMultiplier: 1.0,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        minOrderValue: 199,
      },
      {
        id: 'jaipur',
        name: 'Jaipur',
        state: 'Rajasthan',
        region: 'North',
        stateGstPrefix: '08',
        status: 'ACTIVE',
        totalZones: 3,
        activeZones: 3,
        activePartnerStores: 5,
        activeRiders: 38,
        avgDeliverySlaMins: 15.8,
        defaultSurgeMultiplier: 1.0,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        minOrderValue: 199,
      },
      {
        id: 'kochi',
        name: 'Kochi',
        state: 'Kerala',
        region: 'South',
        stateGstPrefix: '32',
        status: 'LAUNCHING_SOON',
        totalZones: 3,
        activeZones: 0,
        activePartnerStores: 2,
        activeRiders: 0,
        avgDeliverySlaMins: 18.0,
        defaultSurgeMultiplier: 1.0,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        minOrderValue: 199,
      },
    ];

    // 2. Comprehensive Pan-India Hyperlocal Service Zones
    this.serviceAreas = [
      // BENGALURU (Karnataka)
      {
        id: 'zone-blr-01',
        cityId: 'bengaluru',
        name: 'Koramangala & Ejipura Hub',
        city: 'Bengaluru',
        state: 'Karnataka',
        region: 'South',
        pincode: '560034, 560047, 560095',
        coordinates: { lat: 12.9352, lng: 77.6245 },
        radiusKm: 4.5,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '06:00 AM - 11:00 PM',
        activeSellersCount: 3,
        activeRidersCount: 42,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-blr-02',
        cityId: 'bengaluru',
        name: 'HSR Layout & Silk Board',
        city: 'Bengaluru',
        state: 'Karnataka',
        region: 'South',
        pincode: '560102, 560068',
        coordinates: { lat: 12.9121, lng: 77.6446 },
        radiusKm: 5.0,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '06:00 AM - 11:30 PM',
        activeSellersCount: 2,
        activeRidersCount: 36,
        surgeMultiplier: 1.15,
      },
      {
        id: 'zone-blr-03',
        cityId: 'bengaluru',
        name: 'Indiranagar & Domlur Central',
        city: 'Bengaluru',
        state: 'Karnataka',
        region: 'South',
        pincode: '560038, 560071, 560008',
        coordinates: { lat: 12.9784, lng: 77.6408 },
        radiusKm: 4.2,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '06:30 AM - 11:00 PM',
        activeSellersCount: 2,
        activeRidersCount: 28,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-blr-04',
        cityId: 'bengaluru',
        name: 'JP Nagar & Jayanagar',
        city: 'Bengaluru',
        state: 'Karnataka',
        region: 'South',
        pincode: '560078, 560041, 560011',
        coordinates: { lat: 12.9063, lng: 77.5857 },
        radiusKm: 4.8,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '07:00 AM - 10:30 PM',
        activeSellersCount: 1,
        activeRidersCount: 22,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-blr-05',
        cityId: 'bengaluru',
        name: 'Whitefield & ITPL Corridor',
        city: 'Bengaluru',
        state: 'Karnataka',
        region: 'South',
        pincode: '560066, 560048',
        coordinates: { lat: 12.9698, lng: 77.7500 },
        radiusKm: 6.5,
        isActive: true,
        minOrderValue: 249,
        baseDeliveryFee: 35,
        freeDeliveryThreshold: 699,
        operatingHours: '06:00 AM - 10:00 PM',
        activeSellersCount: 1,
        activeRidersCount: 18,
        surgeMultiplier: 1.25,
      },
      {
        id: 'zone-blr-06',
        cityId: 'bengaluru',
        name: 'Electronic City Phase 1 & 2',
        city: 'Bengaluru',
        state: 'Karnataka',
        region: 'South',
        pincode: '560100',
        coordinates: { lat: 12.8452, lng: 77.6602 },
        radiusKm: 5.5,
        isActive: false,
        minOrderValue: 249,
        baseDeliveryFee: 30,
        freeDeliveryThreshold: 599,
        operatingHours: '07:00 AM - 10:00 PM',
        activeSellersCount: 0,
        activeRidersCount: 0,
        surgeMultiplier: 1.0,
      },

      // MUMBAI & MMR (Maharashtra)
      {
        id: 'zone-mum-01',
        cityId: 'mumbai',
        name: 'Andheri East & MIDC Industrial Hub',
        city: 'Mumbai & MMR',
        state: 'Maharashtra',
        region: 'West',
        pincode: '400069, 400093, 400059',
        coordinates: { lat: 19.1136, lng: 72.8697 },
        radiusKm: 4.8,
        isActive: true,
        minOrderValue: 249,
        baseDeliveryFee: 30,
        freeDeliveryThreshold: 599,
        operatingHours: '06:00 AM - 11:30 PM',
        activeSellersCount: 4,
        activeRidersCount: 48,
        surgeMultiplier: 1.2,
      },
      {
        id: 'zone-mum-02',
        cityId: 'mumbai',
        name: 'BKC, Bandra East & Kurla',
        city: 'Mumbai & MMR',
        state: 'Maharashtra',
        region: 'West',
        pincode: '400051, 400070',
        coordinates: { lat: 19.0662, lng: 72.8677 },
        radiusKm: 4.2,
        isActive: true,
        minOrderValue: 249,
        baseDeliveryFee: 30,
        freeDeliveryThreshold: 599,
        operatingHours: '06:00 AM - 11:00 PM',
        activeSellersCount: 3,
        activeRidersCount: 38,
        surgeMultiplier: 1.15,
      },
      {
        id: 'zone-mum-03',
        cityId: 'mumbai',
        name: 'Lower Parel, Worli & Dadar',
        city: 'Mumbai & MMR',
        state: 'Maharashtra',
        region: 'West',
        pincode: '400013, 400018, 400028',
        coordinates: { lat: 18.9986, lng: 72.8306 },
        radiusKm: 4.5,
        isActive: true,
        minOrderValue: 249,
        baseDeliveryFee: 30,
        freeDeliveryThreshold: 599,
        operatingHours: '06:30 AM - 11:00 PM',
        activeSellersCount: 3,
        activeRidersCount: 34,
        surgeMultiplier: 1.1,
      },
      {
        id: 'zone-mum-04',
        cityId: 'mumbai',
        name: 'Thane West & Ghodbunder Corridor',
        city: 'Mumbai & MMR',
        state: 'Maharashtra',
        region: 'West',
        pincode: '400601, 400607, 400615',
        coordinates: { lat: 19.2183, lng: 72.9781 },
        radiusKm: 6.0,
        isActive: true,
        minOrderValue: 249,
        baseDeliveryFee: 35,
        freeDeliveryThreshold: 699,
        operatingHours: '06:00 AM - 10:30 PM',
        activeSellersCount: 2,
        activeRidersCount: 26,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-mum-05',
        cityId: 'mumbai',
        name: 'Navi Mumbai Vashi & Mahape TTC',
        city: 'Mumbai & MMR',
        state: 'Maharashtra',
        region: 'West',
        pincode: '400703, 400705, 400710',
        coordinates: { lat: 19.0771, lng: 72.9986 },
        radiusKm: 5.5,
        isActive: true,
        minOrderValue: 249,
        baseDeliveryFee: 30,
        freeDeliveryThreshold: 599,
        operatingHours: '06:00 AM - 10:30 PM',
        activeSellersCount: 2,
        activeRidersCount: 22,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-mum-06',
        cityId: 'mumbai',
        name: 'Borivali & Kandivali Link Road',
        city: 'Mumbai & MMR',
        state: 'Maharashtra',
        region: 'West',
        pincode: '400092, 400067',
        coordinates: { lat: 19.2307, lng: 72.8567 },
        radiusKm: 4.8,
        isActive: true,
        minOrderValue: 249,
        baseDeliveryFee: 30,
        freeDeliveryThreshold: 599,
        operatingHours: '07:00 AM - 11:00 PM',
        activeSellersCount: 2,
        activeRidersCount: 16,
        surgeMultiplier: 1.0,
      },

      // DELHI NCR (Delhi, Haryana, UP)
      {
        id: 'zone-del-01',
        cityId: 'delhi_ncr',
        name: 'Gurugram Cyber City & Golf Course Rd',
        city: 'Delhi NCR',
        state: 'Haryana',
        region: 'North',
        pincode: '122002, 122003, 122008',
        coordinates: { lat: 28.4595, lng: 77.0266 },
        radiusKm: 5.2,
        isActive: true,
        minOrderValue: 229,
        baseDeliveryFee: 29,
        freeDeliveryThreshold: 549,
        operatingHours: '06:00 AM - 11:30 PM',
        activeSellersCount: 4,
        activeRidersCount: 44,
        surgeMultiplier: 1.15,
      },
      {
        id: 'zone-del-02',
        cityId: 'delhi_ncr',
        name: 'Okhla Industrial Area & Nehru Place',
        city: 'Delhi NCR',
        state: 'Delhi',
        region: 'North',
        pincode: '110020, 110019, 110025',
        coordinates: { lat: 28.5355, lng: 77.2687 },
        radiusKm: 4.5,
        isActive: true,
        minOrderValue: 229,
        baseDeliveryFee: 29,
        freeDeliveryThreshold: 549,
        operatingHours: '06:00 AM - 11:00 PM',
        activeSellersCount: 3,
        activeRidersCount: 38,
        surgeMultiplier: 1.1,
      },
      {
        id: 'zone-del-03',
        cityId: 'delhi_ncr',
        name: 'Noida Sector 62 & Sector 18 Commercial',
        city: 'Delhi NCR',
        state: 'Uttar Pradesh',
        region: 'North',
        pincode: '201301, 201309',
        coordinates: { lat: 28.5708, lng: 77.3271 },
        radiusKm: 5.0,
        isActive: true,
        minOrderValue: 229,
        baseDeliveryFee: 29,
        freeDeliveryThreshold: 549,
        operatingHours: '06:30 AM - 11:00 PM',
        activeSellersCount: 3,
        activeRidersCount: 32,
        surgeMultiplier: 1.05,
      },
      {
        id: 'zone-del-04',
        cityId: 'delhi_ncr',
        name: 'Connaught Place & Karol Bagh Central',
        city: 'Delhi NCR',
        state: 'Delhi',
        region: 'North',
        pincode: '110001, 110005',
        coordinates: { lat: 28.6304, lng: 77.2177 },
        radiusKm: 4.0,
        isActive: true,
        minOrderValue: 229,
        baseDeliveryFee: 29,
        freeDeliveryThreshold: 549,
        operatingHours: '07:00 AM - 10:30 PM',
        activeSellersCount: 2,
        activeRidersCount: 24,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-del-05',
        cityId: 'delhi_ncr',
        name: 'Dwarka & West Delhi Sub-City',
        city: 'Delhi NCR',
        state: 'Delhi',
        region: 'North',
        pincode: '110075, 110078',
        coordinates: { lat: 28.5921, lng: 77.0460 },
        radiusKm: 5.5,
        isActive: true,
        minOrderValue: 229,
        baseDeliveryFee: 29,
        freeDeliveryThreshold: 549,
        operatingHours: '06:30 AM - 10:30 PM',
        activeSellersCount: 2,
        activeRidersCount: 24,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-del-06',
        cityId: 'delhi_ncr',
        name: 'Faridabad Industrial Sector 15-28',
        city: 'Delhi NCR',
        state: 'Haryana',
        region: 'North',
        pincode: '121001, 121007',
        coordinates: { lat: 28.4089, lng: 77.3178 },
        radiusKm: 6.0,
        isActive: false,
        minOrderValue: 249,
        baseDeliveryFee: 35,
        freeDeliveryThreshold: 649,
        operatingHours: '07:00 AM - 09:30 PM',
        activeSellersCount: 0,
        activeRidersCount: 0,
        surgeMultiplier: 1.0,
      },

      // HYDERABAD (Telangana)
      {
        id: 'zone-hyd-01',
        cityId: 'hyderabad',
        name: 'Hitec City & Madhapur IT Zone',
        city: 'Hyderabad',
        state: 'Telangana',
        region: 'South',
        pincode: '500081, 500084',
        coordinates: { lat: 17.4435, lng: 78.3772 },
        radiusKm: 4.6,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '06:00 AM - 11:00 PM',
        activeSellersCount: 3,
        activeRidersCount: 32,
        surgeMultiplier: 1.05,
      },
      {
        id: 'zone-hyd-02',
        cityId: 'hyderabad',
        name: 'Gachibowli & Financial District',
        city: 'Hyderabad',
        state: 'Telangana',
        region: 'South',
        pincode: '500032, 500075',
        coordinates: { lat: 17.4401, lng: 78.3489 },
        radiusKm: 5.0,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '06:00 AM - 11:00 PM',
        activeSellersCount: 2,
        activeRidersCount: 26,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-hyd-03',
        cityId: 'hyderabad',
        name: 'Banjara Hills & Jubilee Hills',
        city: 'Hyderabad',
        state: 'Telangana',
        region: 'South',
        pincode: '500034, 500033',
        coordinates: { lat: 17.4168, lng: 78.4382 },
        radiusKm: 4.2,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '06:30 AM - 10:30 PM',
        activeSellersCount: 2,
        activeRidersCount: 20,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-hyd-04',
        cityId: 'hyderabad',
        name: 'Kukatpally & Miyapur Industrial',
        city: 'Hyderabad',
        state: 'Telangana',
        region: 'South',
        pincode: '500072, 500049',
        coordinates: { lat: 17.4849, lng: 78.4138 },
        radiusKm: 5.2,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '06:30 AM - 10:30 PM',
        activeSellersCount: 2,
        activeRidersCount: 20,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-hyd-05',
        cityId: 'hyderabad',
        name: 'Secunderabad & Begumpet Central',
        city: 'Hyderabad',
        state: 'Telangana',
        region: 'South',
        pincode: '500003, 500016',
        coordinates: { lat: 17.4399, lng: 78.4983 },
        radiusKm: 4.4,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '07:00 AM - 10:00 PM',
        activeSellersCount: 2,
        activeRidersCount: 16,
        surgeMultiplier: 1.0,
      },

      // CHENNAI (Tamil Nadu)
      {
        id: 'zone-chn-01',
        cityId: 'chennai',
        name: 'Guindy Industrial Estate & Ekkattuthangal',
        city: 'Chennai',
        state: 'Tamil Nadu',
        region: 'South',
        pincode: '600032, 600097',
        coordinates: { lat: 13.0067, lng: 80.2025 },
        radiusKm: 4.5,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '06:00 AM - 11:00 PM',
        activeSellersCount: 3,
        activeRidersCount: 28,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-chn-02',
        cityId: 'chennai',
        name: 'OMR IT Expressway & Thoraipakkam',
        city: 'Chennai',
        state: 'Tamil Nadu',
        region: 'South',
        pincode: '600096, 600119',
        coordinates: { lat: 12.9348, lng: 80.2312 },
        radiusKm: 6.0,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 30,
        freeDeliveryThreshold: 599,
        operatingHours: '06:00 AM - 10:30 PM',
        activeSellersCount: 2,
        activeRidersCount: 24,
        surgeMultiplier: 1.1,
      },
      {
        id: 'zone-chn-03',
        cityId: 'chennai',
        name: 'Anna Nagar & Kilpauk',
        city: 'Chennai',
        state: 'Tamil Nadu',
        region: 'South',
        pincode: '600040, 600010',
        coordinates: { lat: 13.0850, lng: 80.2101 },
        radiusKm: 4.2,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '06:30 AM - 10:30 PM',
        activeSellersCount: 2,
        activeRidersCount: 20,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-chn-04',
        cityId: 'chennai',
        name: 'T. Nagar & Alwarpet Commercial',
        city: 'Chennai',
        state: 'Tamil Nadu',
        region: 'South',
        pincode: '600017, 600018',
        coordinates: { lat: 13.0418, lng: 80.2341 },
        radiusKm: 3.8,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '07:00 AM - 10:30 PM',
        activeSellersCount: 2,
        activeRidersCount: 16,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-chn-05',
        cityId: 'chennai',
        name: 'Ambattur Industrial Estate',
        city: 'Chennai',
        state: 'Tamil Nadu',
        region: 'South',
        pincode: '600058',
        coordinates: { lat: 13.0983, lng: 80.1612 },
        radiusKm: 5.5,
        isActive: false,
        minOrderValue: 249,
        baseDeliveryFee: 35,
        freeDeliveryThreshold: 699,
        operatingHours: '07:00 AM - 09:30 PM',
        activeSellersCount: 0,
        activeRidersCount: 0,
        surgeMultiplier: 1.0,
      },

      // PUNE (Maharashtra)
      {
        id: 'zone-pun-01',
        cityId: 'pune',
        name: 'Hinjewadi Infotech Phase 1-3',
        city: 'Pune',
        state: 'Maharashtra',
        region: 'West',
        pincode: '411057',
        coordinates: { lat: 18.5913, lng: 73.7389 },
        radiusKm: 5.5,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '06:00 AM - 11:00 PM',
        activeSellersCount: 3,
        activeRidersCount: 28,
        surgeMultiplier: 1.1,
      },
      {
        id: 'zone-pun-02',
        cityId: 'pune',
        name: 'Hadapsar & Magarpatta Cybercity',
        city: 'Pune',
        state: 'Maharashtra',
        region: 'West',
        pincode: '411028',
        coordinates: { lat: 18.5158, lng: 73.9272 },
        radiusKm: 4.8,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '06:00 AM - 10:30 PM',
        activeSellersCount: 2,
        activeRidersCount: 20,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-pun-03',
        cityId: 'pune',
        name: 'Viman Nagar & Kharadi IT Hub',
        city: 'Pune',
        state: 'Maharashtra',
        region: 'West',
        pincode: '411014',
        coordinates: { lat: 18.5529, lng: 73.9244 },
        radiusKm: 4.5,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '06:30 AM - 11:00 PM',
        activeSellersCount: 2,
        activeRidersCount: 16,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-pun-04',
        cityId: 'pune',
        name: 'Kothrud & Karve Nagar',
        city: 'Pune',
        state: 'Maharashtra',
        region: 'West',
        pincode: '411038, 411052',
        coordinates: { lat: 18.5074, lng: 73.8077 },
        radiusKm: 4.0,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '07:00 AM - 10:00 PM',
        activeSellersCount: 2,
        activeRidersCount: 12,
        surgeMultiplier: 1.0,
      },

      // KOLKATA (West Bengal)
      {
        id: 'zone-kol-01',
        cityId: 'kolkata',
        name: 'Salt Lake Sector V IT Hub',
        city: 'Kolkata',
        state: 'West Bengal',
        region: 'East',
        pincode: '700091',
        coordinates: { lat: 22.5804, lng: 88.4378 },
        radiusKm: 4.5,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '06:30 AM - 10:30 PM',
        activeSellersCount: 3,
        activeRidersCount: 22,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-kol-02',
        cityId: 'kolkata',
        name: 'Rajarhat New Town Financial Hub',
        city: 'Kolkata',
        state: 'West Bengal',
        region: 'East',
        pincode: '700156, 700135',
        coordinates: { lat: 22.5958, lng: 88.4798 },
        radiusKm: 5.5,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '06:00 AM - 10:30 PM',
        activeSellersCount: 2,
        activeRidersCount: 18,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-kol-03',
        cityId: 'kolkata',
        name: 'Park Street, Chowringhee & Central',
        city: 'Kolkata',
        state: 'West Bengal',
        region: 'East',
        pincode: '700016, 700071',
        coordinates: { lat: 22.5535, lng: 88.3534 },
        radiusKm: 3.8,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '07:00 AM - 10:00 PM',
        activeSellersCount: 2,
        activeRidersCount: 14,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-kol-04',
        cityId: 'kolkata',
        name: 'Howrah Industrial Belt & Foundry Zone',
        city: 'Kolkata',
        state: 'West Bengal',
        region: 'East',
        pincode: '711101, 711106',
        coordinates: { lat: 22.5958, lng: 88.2636 },
        radiusKm: 6.0,
        isActive: false,
        minOrderValue: 249,
        baseDeliveryFee: 35,
        freeDeliveryThreshold: 699,
        operatingHours: '07:00 AM - 09:00 PM',
        activeSellersCount: 0,
        activeRidersCount: 0,
        surgeMultiplier: 1.0,
      },

      // AHMEDABAD (Gujarat)
      {
        id: 'zone-ahm-01',
        cityId: 'ahmedabad',
        name: 'SG Highway & Prahladnagar Commercial',
        city: 'Ahmedabad',
        state: 'Gujarat',
        region: 'West',
        pincode: '380015, 380054',
        coordinates: { lat: 23.0134, lng: 72.5097 },
        radiusKm: 4.8,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '06:00 AM - 11:00 PM',
        activeSellersCount: 3,
        activeRidersCount: 26,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-ahm-02',
        cityId: 'ahmedabad',
        name: 'Sanand GIDC & Changodar Industrial Hub',
        city: 'Ahmedabad',
        state: 'Gujarat',
        region: 'West',
        pincode: '382110, 382213',
        coordinates: { lat: 22.9868, lng: 72.3811 },
        radiusKm: 7.0,
        isActive: true,
        minOrderValue: 249,
        baseDeliveryFee: 35,
        freeDeliveryThreshold: 699,
        operatingHours: '06:00 AM - 10:00 PM',
        activeSellersCount: 2,
        activeRidersCount: 20,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-ahm-03',
        cityId: 'ahmedabad',
        name: 'Navrangpura & CG Road Central',
        city: 'Ahmedabad',
        state: 'Gujarat',
        region: 'West',
        pincode: '380009, 380006',
        coordinates: { lat: 23.0373, lng: 72.5613 },
        radiusKm: 3.8,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '07:00 AM - 10:30 PM',
        activeSellersCount: 2,
        activeRidersCount: 16,
        surgeMultiplier: 1.0,
      },

      // JAIPUR (Rajasthan)
      {
        id: 'zone-jai-01',
        cityId: 'jaipur',
        name: 'Sitapura Industrial Area & RIICO Hub',
        city: 'Jaipur',
        state: 'Rajasthan',
        region: 'North',
        pincode: '302022',
        coordinates: { lat: 26.7819, lng: 75.8344 },
        radiusKm: 5.5,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '06:30 AM - 10:30 PM',
        activeSellersCount: 2,
        activeRidersCount: 18,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-jai-02',
        cityId: 'jaipur',
        name: 'Mansarovar & Gopalpura Bypass',
        city: 'Jaipur',
        state: 'Rajasthan',
        region: 'North',
        pincode: '302020',
        coordinates: { lat: 26.8584, lng: 75.7642 },
        radiusKm: 4.8,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '07:00 AM - 10:00 PM',
        activeSellersCount: 2,
        activeRidersCount: 12,
        surgeMultiplier: 1.0,
      },
      {
        id: 'zone-jai-03',
        cityId: 'jaipur',
        name: 'Malviya Nagar & Jagatpura Hub',
        city: 'Jaipur',
        state: 'Rajasthan',
        region: 'North',
        pincode: '302017',
        coordinates: { lat: 26.8532, lng: 75.8167 },
        radiusKm: 4.5,
        isActive: true,
        minOrderValue: 199,
        baseDeliveryFee: 25,
        freeDeliveryThreshold: 499,
        operatingHours: '07:00 AM - 10:00 PM',
        activeSellersCount: 1,
        activeRidersCount: 8,
        surgeMultiplier: 1.0,
      },
    ];

    // 3. Pan-India Verified Sellers & Authorised GST Merchant Partners
    this.sellers = [
      // Bengaluru (KA)
      {
        id: 'sel-01',
        name: 'Koramangala Electrical & Hardware Mart',
        ownerName: 'Suresh Babu',
        hubType: 'Electrical & Industrial Switchgear Hub',
        phone: '+91 98450 12345',
        email: 'suresh.mart@qcom-sellers.in',
        address: '14, 80 Feet Road, 4th Block, Koramangala, Bengaluru 560034',
        areaName: 'Koramangala, Bengaluru',
        gstin: '29ABCDE1234F1Z5',
        panNumber: 'ABCDE1234F',
        bankAccount: {
          accountNumber: '918020045582910',
          ifsc: 'HDFC0000053',
          bankName: 'HDFC Bank, Koramangala',
        },
        status: 'ACTIVE',
        isStoreOnline: true,
        canReceiveOrders: true,
        isOrderingEnabled: true,
        commissionRatePercent: 8.0,
        rating: 4.8,
        totalOrders: 1420,
        activeOrdersCount: 4,
        avgPrepTimeMins: 2.1,
        slaAdherencePercent: 98.4,
        joinedDate: '2025-11-10',
        documents: {
          gstVerified: true,
          panVerified: true,
          bankVerified: true,
          tradeLicenseVerified: true,
        },
      },
      {
        id: 'sel-02',
        name: 'Bengaluru Pipe & Plumbing Depot',
        ownerName: 'M. Venkat Reddy',
        hubType: 'CPVC & Heavy Drainage Depot',
        phone: '+91 98450 23456',
        email: 'venkat.pipes@qcom-sellers.in',
        address: 'Plot 42, Hosur Main Road, Near Silk Board, Bengaluru 560068',
        areaName: 'HSR Layout, Bengaluru',
        gstin: '29BCDEF2345G1Z6',
        panNumber: 'BCDEF2345G',
        bankAccount: {
          accountNumber: '0029104000184920',
          ifsc: 'ICIC0000029',
          bankName: 'ICICI Bank, Silk Board',
        },
        status: 'ACTIVE',
        isStoreOnline: true,
        canReceiveOrders: true,
        isOrderingEnabled: true,
        commissionRatePercent: 8.5,
        rating: 4.9,
        totalOrders: 2180,
        activeOrdersCount: 6,
        avgPrepTimeMins: 2.4,
        slaAdherencePercent: 99.1,
        joinedDate: '2025-10-15',
        documents: {
          gstVerified: true,
          panVerified: true,
          bankVerified: true,
          tradeLicenseVerified: true,
        },
      },
      // Mumbai MMR (MH - GST 27)
      {
        id: 'sel-mum-01',
        name: 'Mumbai Industrial & Marine Fasteners',
        ownerName: 'Rajesh Mehra',
        hubType: 'High-Tensile Anchor & Fasteners Hub',
        phone: '+91 98200 45678',
        email: 'rajesh.mumbai@qcom-sellers.in',
        address: 'Gala 18, MIDC Cross Road B, Andheri East, Mumbai 400093',
        areaName: 'Andheri East, Mumbai',
        gstin: '27AAECM4412F1Z8',
        panNumber: 'AAECM4412F',
        bankAccount: {
          accountNumber: '50200041289190',
          ifsc: 'HDFC0000019',
          bankName: 'HDFC Bank, MIDC Andheri',
        },
        status: 'ACTIVE',
        isStoreOnline: true,
        canReceiveOrders: true,
        isOrderingEnabled: true,
        commissionRatePercent: 8.0,
        rating: 4.9,
        totalOrders: 3120,
        activeOrdersCount: 8,
        avgPrepTimeMins: 1.9,
        slaAdherencePercent: 99.4,
        joinedDate: '2025-09-20',
        documents: {
          gstVerified: true,
          panVerified: true,
          bankVerified: true,
          tradeLicenseVerified: true,
        },
      },
      {
        id: 'sel-mum-02',
        name: 'BKC Electrical Supplies & Industrial Cables',
        ownerName: 'Farhan Merchant',
        hubType: 'Commercial Switchgear & Polycab Depot',
        phone: '+91 98210 99881',
        email: 'farhan.bkc@qcom-sellers.in',
        address: 'Shop 4, Bandra Kurla Complex Road, Bandra East, Mumbai 400051',
        areaName: 'BKC, Mumbai',
        gstin: '27BBCDE8871G1Z4',
        panNumber: 'BBCDE8871G',
        bankAccount: {
          accountNumber: '001105009182',
          ifsc: 'ICIC0000011',
          bankName: 'ICICI Bank, BKC',
        },
        status: 'ACTIVE',
        isStoreOnline: true,
        canReceiveOrders: true,
        isOrderingEnabled: true,
        commissionRatePercent: 8.5,
        rating: 4.8,
        totalOrders: 1890,
        activeOrdersCount: 5,
        avgPrepTimeMins: 2.2,
        slaAdherencePercent: 98.7,
        joinedDate: '2025-11-04',
        documents: {
          gstVerified: true,
          panVerified: true,
          bankVerified: true,
          tradeLicenseVerified: true,
        },
      },
      // Delhi NCR (DL / HR - GST 07 / 06)
      {
        id: 'sel-del-01',
        name: 'DLF Cyber City Pro Hardware & Tools Hub',
        ownerName: 'Harpreet Singh Ahluwalia',
        hubType: 'Bosch Power Tools & Heavy Rigging',
        phone: '+91 98110 33445',
        email: 'harpreet.delhi@qcom-sellers.in',
        address: 'B-14, Phase 2, DLF Industrial Area, Gurugram 122002',
        areaName: 'Cyber City, Gurugram (Delhi NCR)',
        gstin: '06AABCH9912H1Z2',
        panNumber: 'AABCH9912H',
        bankAccount: {
          accountNumber: '110044558821',
          ifsc: 'SBIN0001248',
          bankName: 'SBI, Cyber City Gurugram',
        },
        status: 'ACTIVE',
        isStoreOnline: true,
        canReceiveOrders: true,
        isOrderingEnabled: true,
        commissionRatePercent: 8.5,
        rating: 4.9,
        totalOrders: 2640,
        activeOrdersCount: 7,
        avgPrepTimeMins: 2.0,
        slaAdherencePercent: 99.2,
        joinedDate: '2025-10-18',
        documents: {
          gstVerified: true,
          panVerified: true,
          bankVerified: true,
          tradeLicenseVerified: true,
        },
      },
      {
        id: 'sel-del-02',
        name: 'Okhla Switchgear & Industrial Automation',
        ownerName: 'Sunil Aggarwal',
        hubType: 'L&T & Schneider Distribution Hub',
        phone: '+91 98100 77123',
        email: 'sunil.okhla@qcom-sellers.in',
        address: 'Plot 72, Phase III, Okhla Industrial Area, New Delhi 110020',
        areaName: 'Okhla Industrial, Delhi NCR',
        gstin: '07AACDE1123J1Z9',
        panNumber: 'AACDE1123J',
        bankAccount: {
          accountNumber: '918020088192019',
          ifsc: 'UTIB0000045',
          bankName: 'Axis Bank, Okhla',
        },
        status: 'ACTIVE',
        isStoreOnline: true,
        canReceiveOrders: true,
        isOrderingEnabled: true,
        commissionRatePercent: 8.0,
        rating: 4.7,
        totalOrders: 1450,
        activeOrdersCount: 3,
        avgPrepTimeMins: 2.3,
        slaAdherencePercent: 97.9,
        joinedDate: '2026-01-12',
        documents: {
          gstVerified: true,
          panVerified: true,
          bankVerified: true,
          tradeLicenseVerified: true,
        },
      },
      // Hyderabad (TS - GST 36)
      {
        id: 'sel-hyd-01',
        name: 'Deccan Heavy Tools & Sanitary Hub',
        ownerName: 'N. Ravinder Reddy',
        hubType: 'Industrial Valves & Sanitary Ware Hub',
        phone: '+91 98490 55678',
        email: 'ravinder.deccan@qcom-sellers.in',
        address: 'H-92, Silicon Valley Layout, Madhapur, Hyderabad 500081',
        areaName: 'Hitec City, Hyderabad',
        gstin: '36AABCR7712K1Z3',
        panNumber: 'AABCR7712K',
        bankAccount: {
          accountNumber: '441029104859',
          ifsc: 'HDFC0000422',
          bankName: 'HDFC Bank, Madhapur',
        },
        status: 'ACTIVE',
        isStoreOnline: true,
        canReceiveOrders: true,
        isOrderingEnabled: true,
        commissionRatePercent: 8.0,
        rating: 4.8,
        totalOrders: 1720,
        activeOrdersCount: 4,
        avgPrepTimeMins: 2.1,
        slaAdherencePercent: 98.6,
        joinedDate: '2025-11-28',
        documents: {
          gstVerified: true,
          panVerified: true,
          bankVerified: true,
          tradeLicenseVerified: true,
        },
      },
      // Chennai (TN - GST 33)
      {
        id: 'sel-chn-01',
        name: 'Guindy Industrial Fasteners & Bearings',
        ownerName: 'S. Muruganathan',
        hubType: 'SKF Bearings & Industrial Rivets Depot',
        phone: '+91 98400 88231',
        email: 'murugan.guindy@qcom-sellers.in',
        address: 'Old No 45, Guindy Industrial Estate, Chennai 600032',
        areaName: 'Guindy, Chennai',
        gstin: '33AABCM3312L1Z5',
        panNumber: 'AABCM3312L',
        bankAccount: {
          accountNumber: '6010049281920',
          ifsc: 'IOBA0000104',
          bankName: 'Indian Overseas Bank, Guindy',
        },
        status: 'ACTIVE',
        isStoreOnline: true,
        canReceiveOrders: true,
        isOrderingEnabled: true,
        commissionRatePercent: 8.5,
        rating: 4.8,
        totalOrders: 1540,
        activeOrdersCount: 3,
        avgPrepTimeMins: 2.5,
        slaAdherencePercent: 98.2,
        joinedDate: '2025-12-05',
        documents: {
          gstVerified: true,
          panVerified: true,
          bankVerified: true,
          tradeLicenseVerified: true,
        },
      },
      // Pune (MH - GST 27)
      {
        id: 'sel-pun-01',
        name: 'Hinjewadi Heavy Power Tools & Pneumatics',
        ownerName: 'Nitin Deshmukh',
        hubType: 'Pneumatics & Maktec Tool Depot',
        phone: '+91 98500 11928',
        email: 'nitin.pune@qcom-sellers.in',
        address: 'S.No 24/2, Hinjewadi Phase 1, Infotech Park, Pune 411057',
        areaName: 'Hinjewadi, Pune',
        gstin: '27AABCD6612M1Z1',
        panNumber: 'AABCD6612M',
        bankAccount: {
          accountNumber: '002810294857',
          ifsc: 'MAHB0000142',
          bankName: 'Bank of Maharashtra, Hinjewadi',
        },
        status: 'ACTIVE',
        isStoreOnline: true,
        canReceiveOrders: true,
        isOrderingEnabled: true,
        commissionRatePercent: 8.0,
        rating: 4.8,
        totalOrders: 1320,
        activeOrdersCount: 3,
        avgPrepTimeMins: 2.0,
        slaAdherencePercent: 98.8,
        joinedDate: '2026-01-02',
        documents: {
          gstVerified: true,
          panVerified: true,
          bankVerified: true,
          tradeLicenseVerified: true,
        },
      },
      // Kolkata (WB - GST 19)
      {
        id: 'sel-kol-01',
        name: 'Bengal Electrical & Industrial Warehouse',
        ownerName: 'Subhasish Banerjee',
        hubType: 'Havells & Finolex Master Depot',
        phone: '+91 98300 44556',
        email: 'subhasish.kol@qcom-sellers.in',
        address: 'EP Block, Sector V, Salt Lake City, Kolkata 700091',
        areaName: 'Salt Lake Sector V, Kolkata',
        gstin: '19AABCB5512N1Z7',
        panNumber: 'AABCB5512N',
        bankAccount: {
          accountNumber: '110029384756',
          ifsc: 'UBIN0542918',
          bankName: 'Union Bank of India, Salt Lake',
        },
        status: 'ACTIVE',
        isStoreOnline: true,
        canReceiveOrders: true,
        isOrderingEnabled: true,
        commissionRatePercent: 8.5,
        rating: 4.7,
        totalOrders: 1180,
        activeOrdersCount: 2,
        avgPrepTimeMins: 2.6,
        slaAdherencePercent: 97.6,
        joinedDate: '2026-01-15',
        documents: {
          gstVerified: true,
          panVerified: true,
          bankVerified: true,
          tradeLicenseVerified: true,
        },
      },
      // Ahmedabad (GJ - GST 24)
      {
        id: 'sel-ahm-01',
        name: 'Gujarat Automation & Brass Valve Hub',
        ownerName: 'Jignesh Patel',
        hubType: 'Brass Fittings & Heavy Gate Valves',
        phone: '+91 98250 77889',
        email: 'jignesh.ahm@qcom-sellers.in',
        address: 'Titanium City Centre, 100 Ft Anandnagar Rd, Ahmedabad 380015',
        areaName: 'SG Highway, Ahmedabad',
        gstin: '24AABCP4412P1Z0',
        panNumber: 'AABCP4412P',
        bankAccount: {
          accountNumber: '5010049281729',
          ifsc: 'KKBK0000812',
          bankName: 'Kotak Mahindra Bank, Anandnagar',
        },
        status: 'ACTIVE',
        isStoreOnline: true,
        canReceiveOrders: true,
        isOrderingEnabled: true,
        commissionRatePercent: 8.0,
        rating: 4.9,
        totalOrders: 1490,
        activeOrdersCount: 4,
        avgPrepTimeMins: 1.8,
        slaAdherencePercent: 99.3,
        joinedDate: '2025-11-20',
        documents: {
          gstVerified: true,
          panVerified: true,
          bankVerified: true,
          tradeLicenseVerified: true,
        },
      },
    ];

    // 4. Pan-India Dedicated Delivery Fleet
    this.riders = [
      // Bengaluru
      {
        id: 'rdr-301',
        name: 'Manjunath Gowda',
        phone: '+91 97410 11223',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
        vehicleType: 'EV_SCOOTER',
        vehicleNumber: 'KA-05-EV-1029',
        status: 'ON_DELIVERY',
        currentLocation: { lat: 12.9341, lng: 77.6210, areaName: 'Koramangala 4th Block, Bengaluru' },
        currentOrderId: 'ord-102934',
        batteryPercent: 88,
        rating: 4.9,
        totalDeliveries: 412,
        todayDeliveries: 8,
        todayEarnings: 580,
        activeSince: '6 months ago',
        documents: { drivingLicenseVerified: true, rcVerified: true, aadharVerified: true, backgroundCheckPassed: true },
      },
      {
        id: 'rdr-302',
        name: 'Ravi Kumar Naik',
        phone: '+91 97410 22334',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
        vehicleType: 'E_LOADER',
        vehicleNumber: 'KA-01-MJ-8821',
        status: 'ONLINE',
        currentLocation: { lat: 12.9140, lng: 77.6410, areaName: 'HSR Sector 2, Bengaluru' },
        batteryPercent: 74,
        rating: 4.8,
        totalDeliveries: 560,
        todayDeliveries: 6,
        todayEarnings: 490,
        activeSince: '8 months ago',
        documents: { drivingLicenseVerified: true, rcVerified: true, aadharVerified: true, backgroundCheckPassed: true },
      },
      // Mumbai MMR
      {
        id: 'rdr-mum-01',
        name: 'Sachin Sawant',
        phone: '+91 98201 55667',
        avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80',
        vehicleType: 'EV_SCOOTER',
        vehicleNumber: 'MH-02-EV-4412',
        status: 'ONLINE',
        currentLocation: { lat: 19.1120, lng: 72.8680, areaName: 'MIDC Andheri East, Mumbai' },
        batteryPercent: 92,
        rating: 4.9,
        totalDeliveries: 620,
        todayDeliveries: 9,
        todayEarnings: 690,
        activeSince: '9 months ago',
        documents: { drivingLicenseVerified: true, rcVerified: true, aadharVerified: true, backgroundCheckPassed: true },
      },
      {
        id: 'rdr-mum-02',
        name: 'Ganesh Shinde',
        phone: '+91 98202 88990',
        avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=120&auto=format&fit=crop&q=80',
        vehicleType: 'E_LOADER',
        vehicleNumber: 'MH-03-BJ-9031',
        status: 'ON_DELIVERY',
        currentLocation: { lat: 19.0650, lng: 72.8660, areaName: 'BKC G-Block, Mumbai' },
        currentOrderId: 'ord-mum-101',
        batteryPercent: 68,
        rating: 4.8,
        totalDeliveries: 490,
        todayDeliveries: 7,
        todayEarnings: 590,
        activeSince: '7 months ago',
        documents: { drivingLicenseVerified: true, rcVerified: true, aadharVerified: true, backgroundCheckPassed: true },
      },
      // Delhi NCR
      {
        id: 'rdr-del-01',
        name: 'Kuldeep Yadav',
        phone: '+91 98111 22334',
        avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
        vehicleType: 'EV_SCOOTER',
        vehicleNumber: 'HR-26-EV-7821',
        status: 'ONLINE',
        currentLocation: { lat: 28.4580, lng: 77.0250, areaName: 'Cyber City Sector 24, Gurugram' },
        batteryPercent: 85,
        rating: 4.9,
        totalDeliveries: 580,
        todayDeliveries: 8,
        todayEarnings: 640,
        activeSince: '8 months ago',
        documents: { drivingLicenseVerified: true, rcVerified: true, aadharVerified: true, backgroundCheckPassed: true },
      },
      {
        id: 'rdr-del-02',
        name: 'Amit Bhati',
        phone: '+91 98112 44556',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
        vehicleType: 'E_LOADER',
        vehicleNumber: 'DL-3S-EV-4411',
        status: 'ONLINE',
        currentLocation: { lat: 28.5340, lng: 77.2670, areaName: 'Okhla Phase III, Delhi' },
        batteryPercent: 78,
        rating: 4.8,
        totalDeliveries: 410,
        todayDeliveries: 5,
        todayEarnings: 420,
        activeSince: '5 months ago',
        documents: { drivingLicenseVerified: true, rcVerified: true, aadharVerified: true, backgroundCheckPassed: true },
      },
      // Hyderabad
      {
        id: 'rdr-hyd-01',
        name: 'Venkatesh Rao',
        phone: '+91 98491 66778',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
        vehicleType: 'EV_SCOOTER',
        vehicleNumber: 'TS-09-EV-3312',
        status: 'ONLINE',
        currentLocation: { lat: 17.4420, lng: 78.3750, areaName: 'Madhapur Main Rd, Hyderabad' },
        batteryPercent: 90,
        rating: 4.9,
        totalDeliveries: 390,
        todayDeliveries: 6,
        todayEarnings: 480,
        activeSince: '6 months ago',
        documents: { drivingLicenseVerified: true, rcVerified: true, aadharVerified: true, backgroundCheckPassed: true },
      },
      // Chennai
      {
        id: 'rdr-chn-01',
        name: 'K. Saravanan',
        phone: '+91 98401 77889',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
        vehicleType: 'EV_SCOOTER',
        vehicleNumber: 'TN-07-EV-5542',
        status: 'ONLINE',
        currentLocation: { lat: 13.0050, lng: 80.2010, areaName: 'Guindy Estate Road, Chennai' },
        batteryPercent: 82,
        rating: 4.8,
        totalDeliveries: 440,
        todayDeliveries: 7,
        todayEarnings: 530,
        activeSince: '7 months ago',
        documents: { drivingLicenseVerified: true, rcVerified: true, aadharVerified: true, backgroundCheckPassed: true },
      },
      // Pune
      {
        id: 'rdr-pun-01',
        name: 'Amol Jadhav',
        phone: '+91 98501 33445',
        avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80',
        vehicleType: 'EV_SCOOTER',
        vehicleNumber: 'MH-12-EV-9912',
        status: 'ONLINE',
        currentLocation: { lat: 18.5900, lng: 73.7370, areaName: 'Hinjewadi Phase 1, Pune' },
        batteryPercent: 88,
        rating: 4.9,
        totalDeliveries: 380,
        todayDeliveries: 6,
        todayEarnings: 470,
        activeSince: '5 months ago',
        documents: { drivingLicenseVerified: true, rcVerified: true, aadharVerified: true, backgroundCheckPassed: true },
      },
    ];

    // 5. Pan-India Live Orders
    this.orders = [
      // Bengaluru Order
      {
        id: 'ord-102934',
        orderNumber: 'QC-102934',
        customer: {
          id: 'cust-01',
          name: 'Ashok Kumar (Master Electrician)',
          phone: '+91 98451 99881',
          accountType: 'electrician',
          businessName: 'AK Electrical Contracting & Maintenance',
          gstin: '29AAAPL1234F1Z8',
        },
        jobSite: {
          address: 'Prestige Falcon Tower, Site 4B, 3rd Floor fitout, Koramangala 4th Block, Bengaluru',
          landmark: 'Opp. Sony Signal Forum Mall Backgate',
          gateCode: 'GATE-03',
          contactPhone: '+91 98451 99881',
          areaName: 'Koramangala, Bengaluru',
        },
        seller: {
          id: 'sel-01',
          name: 'Koramangala Electrical & Hardware Mart',
          hubType: 'Electrical Switchgear Hub',
          phone: '+91 98450 12345',
          address: '14, 80 Feet Road, 4th Block, Koramangala, Bengaluru',
          gstin: '29ABCDE1234F1Z5',
        },
        rider: {
          id: 'rdr-301',
          name: 'Manjunath Gowda',
          phone: '+91 97410 11223',
          vehicle: 'KA-05-EV-1029',
          rating: 4.9,
          currentSpeedKmH: 28,
          distanceMeters: 450,
        },
        items: [
          {
            productId: 'prod-01',
            productName: 'Schneider Electric 32A Triple Pole MCB (C-Curve 10kA)',
            brand: 'Schneider Electric',
            category: 'Electrical & Switchgear',
            unit: 'Piece',
            price: 580,
            quantity: 4,
            hsnCode: '85362030',
            gstRate: 18,
          },
          {
            productId: 'prod-02',
            productName: 'Polycab 4.0 sq mm Multi-strand Copper Wire (Red 90m)',
            brand: 'Polycab',
            category: 'Cables & Wiring',
            unit: 'Roll',
            price: 2450,
            quantity: 2,
            hsnCode: '85444990',
            gstRate: 18,
          },
        ],
        pricing: {
          subtotal: 7220,
          deliveryFee: 0,
          urgencyFee: 15,
          discount: 150,
          couponCode: 'PROBUILD150',
          tax: 1272.6,
          total: 8357.6,
          itcAmount: 1272.6,
        },
        payment: {
          status: 'PAID',
          method: 'UPI',
          transactionId: 'UPI-RAZ-99102934817',
          paidAt: '08:42 AM IST',
        },
        status: 'out_for_delivery',
        deliveryOtp: '7492',
        placedAt: '08:40 AM IST',
        estimatedDeliveryAt: '08:58 AM IST (18m SLA)',
        timeline: [
          { stage: 'Order Placed', timestamp: '08:40 AM', description: 'Contractor placed verified order with GST claim', completed: true },
          { stage: 'Partner Store Packed', timestamp: '08:43 AM', description: 'Koramangala Partner Store verified and sealed QR bags', completed: true },
          { stage: 'Rider Picked Up', timestamp: '08:47 AM', description: 'Rider Manjunath Gowda in transit with EV fleet', completed: true },
          { stage: 'Jobsite Delivery', timestamp: 'Pending', description: 'Jobsite handover pending OTP verification', completed: false },
        ],
      },

      // Mumbai MMR Order
      {
        id: 'ord-mum-101',
        orderNumber: 'QC-MUM-8821',
        customer: {
          id: 'cust-mum-01',
          name: 'Nikhil Rane (Chief MEP Contractor)',
          phone: '+91 98200 11992',
          accountType: 'contractor',
          businessName: 'Rane MEP Infrastructures LLP',
          gstin: '27AABCR9912M1Z2',
        },
        jobSite: {
          address: 'Godrej One Tower, 7th Floor Fitout Wing B, Pirojshanagar, Vikhroli East, Mumbai',
          landmark: 'Near Eastern Express Highway Entry',
          gateCode: 'CARGO-GATE-2',
          contactPhone: '+91 98200 11992',
          areaName: 'Vikhroli East, Mumbai',
        },
        seller: {
          id: 'sel-mum-01',
          name: 'Mumbai Industrial & Marine Fasteners',
          hubType: 'High-Tensile Fasteners Hub',
          phone: '+91 98200 45678',
          address: 'Gala 18, MIDC Cross Road B, Andheri East, Mumbai',
          gstin: '27AAECM4412F1Z8',
        },
        rider: {
          id: 'rdr-mum-02',
          name: 'Ganesh Shinde',
          phone: '+91 98202 88990',
          vehicle: 'MH-03-BJ-9031',
          rating: 4.8,
          currentSpeedKmH: 32,
          distanceMeters: 800,
        },
        items: [
          {
            productId: 'prod-03',
            productName: 'Hilti M12 Drop-in Heavy Concrete Anchors (Box of 50)',
            brand: 'Hilti',
            category: 'Fasteners & Rigging',
            unit: 'Box',
            price: 1850,
            quantity: 3,
            hsnCode: '73181500',
            gstRate: 18,
          },
        ],
        pricing: {
          subtotal: 5550,
          deliveryFee: 0,
          urgencyFee: 15,
          discount: 0,
          tax: 999,
          total: 6564,
          itcAmount: 999,
        },
        payment: {
          status: 'PAID',
          method: 'TRADE_CREDIT',
          transactionId: 'TC-RANE-20260825',
          paidAt: '08:35 AM IST',
        },
        status: 'out_for_delivery',
        deliveryOtp: '3819',
        placedAt: '08:32 AM IST',
        estimatedDeliveryAt: '08:50 AM IST (18m SLA)',
        timeline: [
          { stage: 'Order Placed', timestamp: '08:32 AM', description: 'Contractor placed order using 30-Day Trade Credit', completed: true },
          { stage: 'Partner Store Packed', timestamp: '08:36 AM', description: 'Andheri Partner Store packaged concrete anchors', completed: true },
          { stage: 'Rider Picked Up', timestamp: '08:41 AM', description: 'Rider Ganesh Shinde departed on E-Loader', completed: true },
          { stage: 'Jobsite Handover', timestamp: 'Pending', description: 'Delivery OTP verification required at gate', completed: false },
        ],
      },

      // Delhi NCR Order
      {
        id: 'ord-del-102',
        orderNumber: 'QC-DEL-4419',
        customer: {
          id: 'cust-del-01',
          name: 'Vipin Chaudhary (HVAC Engineer)',
          phone: '+91 98110 88771',
          accountType: 'contractor',
          businessName: 'Apex Aircon Engineering Works',
          gstin: '07AAACA4412P1Z9',
        },
        jobSite: {
          address: 'DLF Cyber City, Building 10, Tower C, DLF Phase 2, Gurugram, Haryana',
          landmark: 'Near Rapid Metro Cyber City Station',
          gateCode: 'TOWER-C-LOADING',
          contactPhone: '+91 98110 88771',
          areaName: 'Cyber City, Gurugram (Delhi NCR)',
        },
        seller: {
          id: 'sel-del-01',
          name: 'DLF Cyber City Pro Hardware & Tools Hub',
          hubType: 'Bosch Power Tools & Heavy Rigging',
          phone: '+91 98110 33445',
          address: 'B-14, Phase 2, DLF Industrial Area, Gurugram',
          gstin: '06AABCH9912H1Z2',
        },
        items: [
          {
            productId: 'prod-04',
            productName: 'Bosch Professional GSB 600 Heavy Impact Drill 13mm',
            brand: 'Bosch',
            category: 'Power Tools',
            unit: 'Unit',
            price: 3499,
            quantity: 1,
            hsnCode: '84672100',
            gstRate: 18,
          },
        ],
        pricing: {
          subtotal: 3499,
          deliveryFee: 0,
          urgencyFee: 15,
          discount: 100,
          couponCode: 'BOSCH100',
          tax: 611.82,
          total: 4025.82,
          itcAmount: 611.82,
        },
        payment: {
          status: 'PAID',
          method: 'UPI',
          transactionId: 'UPI-HDFC-8829104819',
          paidAt: '08:48 AM IST',
        },
        status: 'packed',
        deliveryOtp: '9184',
        placedAt: '08:46 AM IST',
        estimatedDeliveryAt: '09:05 AM IST (19m SLA)',
        timeline: [
          { stage: 'Order Placed', timestamp: '08:46 AM', description: 'Urgent tool breakdown order placed', completed: true },
          { stage: 'Partner Store Packed', timestamp: '08:49 AM', description: 'Cyber City Partner Store packed Bosch drill & spare chucks', completed: true },
          { stage: 'Awaiting Rider Assignment', timestamp: 'Pending', description: 'Dispatch engine searching for nearby EV riders in Cyber City', completed: false },
        ],
      },

      // Hyderabad Order
      {
        id: 'ord-hyd-103',
        orderNumber: 'QC-HYD-5512',
        customer: {
          id: 'cust-hyd-01',
          name: 'K. Sridhar (Senior Plumber)',
          phone: '+91 98490 22331',
          accountType: 'plumber',
          businessName: 'Sri Sai MEP Solutions',
          gstin: '36AAAFS1123Q1Z1',
        },
        jobSite: {
          address: 'My Home Bhooja, Block D, Flat 1402, HITEC City, Hyderabad',
          landmark: 'Opp. Biodiversity Park',
          contactPhone: '+91 98490 22331',
          areaName: 'Hitec City, Hyderabad',
        },
        seller: {
          id: 'sel-hyd-01',
          name: 'Deccan Heavy Tools & Sanitary Hub',
          hubType: 'Industrial Valves & Sanitary Ware Hub',
          phone: '+91 98490 55678',
          address: 'H-92, Silicon Valley Layout, Madhapur, Hyderabad',
          gstin: '36AABCR7712K1Z3',
        },
        items: [
          {
            productId: 'prod-05',
            productName: 'Astral CPVC Pro High-Pressure 1-inch Ball Valve (Heavy Duty)',
            brand: 'Astral Pipes',
            category: 'Plumbing & Drainage',
            unit: 'Piece',
            price: 340,
            quantity: 6,
            hsnCode: '84818030',
            gstRate: 18,
          },
        ],
        pricing: {
          subtotal: 2040,
          deliveryFee: 25,
          urgencyFee: 15,
          discount: 0,
          tax: 367.2,
          total: 2447.2,
          itcAmount: 367.2,
        },
        payment: {
          status: 'PAID',
          method: 'NETBANKING',
          transactionId: 'NB-HDFC-99182948',
          paidAt: '08:44 AM IST',
        },
        status: 'picking',
        deliveryOtp: '4421',
        placedAt: '08:44 AM IST',
        estimatedDeliveryAt: '09:02 AM IST (18m SLA)',
        timeline: [
          { stage: 'Order Placed', timestamp: '08:44 AM', description: 'Emergency CPVC valve repair order received', completed: true },
          { stage: 'Picking in Progress', timestamp: '08:45 AM', description: 'Deccan Hub picking items from shelf A-4', completed: true },
        ],
      },
    ];

    // 6. Pan-India Inventory SKUs
    this.products = [
      {
        id: 'prod-01',
        name: 'Schneider Electric 32A Triple Pole MCB (C-Curve 10kA)',
        category: 'Electrical & Switchgear',
        subcategory: 'Circuit Breakers',
        brand: 'Schneider Electric',
        price: 580,
        mrp: 750,
        unit: 'Piece',
        stockCount: 142,
        minStockAlert: 20,
        hsnCode: '85362030',
        gstRatePercent: 18,
        inStock: true,
        sellerId: 'sel-01',
        sellerName: 'Koramangala Electrical & Hardware Mart',
        rating: 4.9,
      },
      {
        id: 'prod-02',
        name: 'Polycab 4.0 sq mm Multi-strand Copper Wire (Red 90m)',
        category: 'Cables & Wiring',
        subcategory: 'FR Building Wires',
        brand: 'Polycab',
        price: 2450,
        mrp: 3100,
        unit: 'Roll',
        stockCount: 48,
        minStockAlert: 15,
        hsnCode: '85444990',
        gstRatePercent: 18,
        inStock: true,
        sellerId: 'sel-01',
        sellerName: 'Koramangala Electrical & Hardware Mart',
        rating: 4.8,
      },
      {
        id: 'prod-03',
        name: 'Hilti M12 Drop-in Heavy Concrete Anchors (Box of 50)',
        category: 'Fasteners & Rigging',
        subcategory: 'Concrete Anchors',
        brand: 'Hilti',
        price: 1850,
        mrp: 2300,
        unit: 'Box',
        stockCount: 84,
        minStockAlert: 25,
        hsnCode: '73181500',
        gstRatePercent: 18,
        inStock: true,
        sellerId: 'sel-mum-01',
        sellerName: 'Mumbai Industrial & Marine Fasteners',
        rating: 4.9,
      },
      {
        id: 'prod-04',
        name: 'Bosch Professional GSB 600 Heavy Impact Drill 13mm',
        category: 'Power Tools',
        subcategory: 'Impact Drills',
        brand: 'Bosch',
        price: 3499,
        mrp: 4500,
        unit: 'Unit',
        stockCount: 28,
        minStockAlert: 8,
        hsnCode: '84672100',
        gstRatePercent: 18,
        inStock: true,
        sellerId: 'sel-del-01',
        sellerName: 'DLF Cyber City Pro Hardware & Tools Hub',
        rating: 4.9,
      },
      {
        id: 'prod-05',
        name: 'Astral CPVC Pro High-Pressure 1-inch Ball Valve (Heavy Duty)',
        category: 'Plumbing & Drainage',
        subcategory: 'Valves & Fittings',
        brand: 'Astral Pipes',
        price: 340,
        mrp: 460,
        unit: 'Piece',
        stockCount: 95,
        minStockAlert: 20,
        hsnCode: '84818030',
        gstRatePercent: 18,
        inStock: true,
        sellerId: 'sel-hyd-01',
        sellerName: 'Deccan Heavy Tools & Sanitary Hub',
        rating: 4.8,
      },
      {
        id: 'prod-06',
        name: 'SKF 6205-2RSH Deep Groove Heavy Radial Ball Bearing',
        category: 'Industrial Bearings',
        subcategory: 'Ball Bearings',
        brand: 'SKF',
        price: 420,
        mrp: 550,
        unit: 'Piece',
        stockCount: 160,
        minStockAlert: 30,
        hsnCode: '84821011',
        gstRatePercent: 18,
        inStock: true,
        sellerId: 'sel-chn-01',
        sellerName: 'Guindy Industrial Fasteners & Bearings',
        rating: 4.9,
      },
    ];

    // 7. Customers across Pan-India
    this.customers = [
      {
        id: 'cust-01',
        name: 'Ashok Kumar',
        phone: '+91 98451 99881',
        email: 'ashok.mep@ak-electricals.in',
        accountType: 'electrician',
        companyName: 'AK Electrical Contracting & Maintenance',
        status: 'ACTIVE',
        totalOrders: 64,
        totalSpend: 248900,
        savedGstins: [{ gstin: '29AAAPL1234F1Z8', legalName: 'AK Electrical Contracting', state: 'Karnataka' }],
        addresses: [{ label: 'Prestige Falcon Tower Jobsite', address: 'Site 4B, Koramangala 4th Block', areaName: 'Koramangala, Bengaluru' }],
        createdAt: '2025-08-14',
        lastActive: 'Just now',
      },
      {
        id: 'cust-mum-01',
        name: 'Nikhil Rane',
        phone: '+91 98200 11992',
        email: 'nikhil@ranemep.com',
        accountType: 'contractor',
        companyName: 'Rane MEP Infrastructures LLP',
        status: 'ACTIVE',
        totalOrders: 112,
        totalSpend: 782400,
        savedGstins: [{ gstin: '27AABCR9912M1Z2', legalName: 'Rane MEP Infrastructures LLP', state: 'Maharashtra' }],
        addresses: [{ label: 'Godrej One Vikhroli Site', address: '7th Floor Wing B, Pirojshanagar', areaName: 'Vikhroli East, Mumbai' }],
        createdAt: '2025-06-10',
        lastActive: '5 mins ago',
      },
      {
        id: 'cust-del-01',
        name: 'Vipin Chaudhary',
        phone: '+91 98110 88771',
        email: 'vipin@apexaircon.in',
        accountType: 'contractor',
        companyName: 'Apex Aircon Engineering Works',
        status: 'ACTIVE',
        totalOrders: 89,
        totalSpend: 541200,
        savedGstins: [{ gstin: '07AAACA4412P1Z9', legalName: 'Apex Aircon Engineering', state: 'Delhi' }],
        addresses: [{ label: 'DLF Cyber City Building 10', address: 'Tower C Fitout Wing', areaName: 'Cyber City, Gurugram' }],
        createdAt: '2025-07-22',
        lastActive: '12 mins ago',
      },
    ];

    // 8. Refunds
    this.refunds = [
      {
        id: 'ref-001',
        orderId: 'ord-102925',
        orderNumber: 'QC-102925',
        customerName: 'Maheshwari Plumbing Works (Bengaluru)',
        amount: 795,
        maxRefundable: 795,
        reason: 'Customer cancelled prior to partner store picking due to incorrect pipe diameter selected',
        requestedBy: 'Customer Support (Karthik Raja)',
        status: 'COMPLETED',
        createdAt: '25 Aug 2026, 07:55 AM',
        approvedBy: 'Deepak Mehrotra (Finance Admin)',
        approvedAt: '25 Aug 2026, 08:00 AM',
        transactionId: 'REF-UPI-99281048192',
      },
      {
        id: 'ref-mum-002',
        orderId: 'ord-mum-991',
        orderNumber: 'QC-MUM-7712',
        customerName: 'Reliable Electrical Contractors (Mumbai)',
        amount: 1450,
        maxRefundable: 1450,
        reason: 'Damaged packaging detected during unboxing on jobsite; immediate credit note requested',
        requestedBy: 'Customer Support (Karthik Raja)',
        status: 'PENDING',
        createdAt: '25 Aug 2026, 08:30 AM',
      },
    ];

    // 9. Seller Settlements across Indian States
    this.settlements = [
      {
        id: 'set-blr-01',
        sellerId: 'sel-01',
        sellerName: 'Koramangala Electrical & Hardware Mart (Bengaluru, KA)',
        periodStart: '18 Aug 2026',
        periodEnd: '24 Aug 2026',
        grossSales: 184500,
        commissionDeducted: 14760,
        refundsAdjusted: 795,
        tdsDeducted: 1845,
        netPayable: 167100,
        status: 'PAID',
        payoutDate: '25 Aug 2026, 06:00 AM',
        utrNumber: 'HDFCN26082500192',
      },
      {
        id: 'set-mum-01',
        sellerId: 'sel-mum-01',
        sellerName: 'Mumbai Industrial & Marine Fasteners (Mumbai, MH)',
        periodStart: '18 Aug 2026',
        periodEnd: '24 Aug 2026',
        grossSales: 298400,
        commissionDeducted: 23872,
        refundsAdjusted: 0,
        tdsDeducted: 2984,
        netPayable: 271544,
        status: 'PAID',
        payoutDate: '25 Aug 2026, 06:00 AM',
        utrNumber: 'ICICN26082500812',
      },
      {
        id: 'set-del-01',
        sellerId: 'sel-del-01',
        sellerName: 'DLF Cyber City Pro Hardware Hub (Delhi NCR)',
        periodStart: '18 Aug 2026',
        periodEnd: '24 Aug 2026',
        grossSales: 215600,
        commissionDeducted: 18326,
        refundsAdjusted: 1200,
        tdsDeducted: 2156,
        netPayable: 193918,
        status: 'PENDING',
      },
    ];

    // 10. Pan-India Support Desk Tickets
    this.supportTickets = [
      {
        id: 'tkt-01',
        ticketNumber: 'TKT-2026-891',
        raisedByName: 'Nikhil Rane (Contractor)',
        raisedByType: 'CONTRACTOR',
        customerName: 'Nikhil Rane',
        customerPhone: '+91 98200 11992',
        orderNumber: 'QC-MUM-8821',
        category: 'DELIVERY_DELAY',
        priority: 'HIGH',
        status: 'IN_PROGRESS',
        subject: 'Jobsite Gate Pass issue at Vikhroli Godrej Tower',
        description: 'Security asking for contractor escort before letting EV loader rider into cargo elevator.',
        assignedTo: 'Karthik Raja',
        createdAt: '08:44 AM IST, Today',
      },
      {
        id: 'tkt-02',
        ticketNumber: 'TKT-2026-892',
        raisedByName: 'Suresh Babu (Seller)',
        raisedByType: 'SELLER',
        customerName: 'Koramangala Electrical Mart',
        customerPhone: '+91 98450 12345',
        category: 'GENERAL',
        priority: 'MEDIUM',
        status: 'OPEN',
        subject: 'GST Invoice ITC summary discrepancy for B2B order QC-102934',
        description: 'Seller seeking clarification on reverse charge mechanism for inter-state customer claiming ITC in KA.',
        assignedTo: 'Sunita Mehra (Finance)',
        createdAt: '08:12 AM IST, Today',
      },
    ];

    // 11. Initial Audit Trail
    this.auditLogs = [
      {
        id: 'aud-001',
        adminId: 'adm-001',
        adminName: 'Vikram Malhotra',
        adminRole: 'SUPER_ADMIN',
        action: 'PAN_INDIA_REGIONAL_GRID_ACTIVATED',
        targetEntity: 'ServiceAreaZone',
        targetId: 'PAN_INDIA_ALL',
        details: 'Enabled All-India multi-region logistics grid across 9 metropolitan states (34 Hubs)',
        ipAddress: '103.212.144.22',
        timestamp: '25 Aug 2026, 07:00 AM',
        status: 'SUCCESS',
      },
      {
        id: 'aud-002',
        adminId: 'adm-003',
        adminName: 'Anand Kulkarni',
        adminRole: 'SELLER_MANAGER',
        action: 'SELLER_KYC_VERIFIED',
        targetEntity: 'Seller',
        targetId: 'sel-mum-01',
        details: 'Verified Maharashtra GSTIN 27AAECM4412F1Z8 and bank mandate for Mumbai Fasteners Hub',
        ipAddress: '49.207.211.89',
        timestamp: '25 Aug 2026, 07:30 AM',
        status: 'SUCCESS',
      },
      {
        id: 'aud-003',
        adminId: 'adm-005',
        adminName: 'Sunita Mehra',
        adminRole: 'FINANCE_ADMIN',
        action: 'SELLER_PAYOUT_EXECUTED',
        targetEntity: 'Settlement',
        targetId: 'set-mum-01',
        details: 'Executed NEFT payout ₹2,71,544 to Mumbai Industrial Fasteners (UTR: ICICN26082500812)',
        ipAddress: '106.51.78.114',
        timestamp: '25 Aug 2026, 08:00 AM',
        status: 'SUCCESS',
      },
    ];

    // 4. Promotions & Coupons Engine Initial Data
    this.promotions = [
      {
        id: 'prm-01',
        code: 'BUILDER50',
        name: 'Monsoon Contractor Kickstart',
        type: 'COUPON',
        discountValue: 50,
        isPercentage: false,
        minOrderValue: 499,
        maxDiscountCap: 50,
        fundingSource: 'PLATFORM',
        fundingSharePercent: { platform: 100, seller: 0, brand: 0 },
        validFrom: '2026-08-01',
        validUntil: '2026-09-30',
        usageCount: 1420,
        maxUsageLimit: 5000,
        status: 'ACTIVE',
        createdBy: 'Siddharth Varma (Marketing)',
      },
      {
        id: 'prm-02',
        code: 'HAVELLS15',
        name: 'Havells Switchgear & Wire Blitz',
        type: 'PERCENTAGE_DISCOUNT',
        discountValue: 15,
        isPercentage: true,
        minOrderValue: 1499,
        maxDiscountCap: 450,
        fundingSource: 'BRAND',
        fundingSharePercent: { platform: 0, seller: 0, brand: 100 },
        applicableBrand: 'Havells',
        applicableCategory: 'Electrical Switchgears',
        validFrom: '2026-08-15',
        validUntil: '2026-08-31',
        usageCount: 680,
        maxUsageLimit: 2000,
        status: 'ACTIVE',
        createdBy: 'Siddharth Varma (Marketing)',
      },
      {
        id: 'prm-03',
        code: 'FREEDEL299',
        name: 'Express 15-Min Free Delivery Offer',
        type: 'FREE_DELIVERY',
        discountValue: 35,
        isPercentage: false,
        minOrderValue: 299,
        maxDiscountCap: 35,
        fundingSource: 'SHARED',
        fundingSharePercent: { platform: 60, seller: 40, brand: 0 },
        validFrom: '2026-08-01',
        validUntil: '2026-10-31',
        usageCount: 3120,
        maxUsageLimit: 10000,
        status: 'ACTIVE',
        createdBy: 'Siddharth Varma (Marketing)',
      },
    ];

    // 5. Retail Media Sponsored Ads Engine Initial Data
    this.sponsoredAds = [
      {
        id: 'ad-coca-cola-01',
        campaignName: 'Coca-Cola Summer Refreshment for On-site Crews',
        advertiserBrand: 'Coca-Cola India',
        brandContactEmail: 'brand.campaigns@coca-cola.in',
        placement: 'HOME_TOP_BANNER',
        startDate: '2026-08-01',
        endDate: '2026-08-31',
        totalBudget: 250000,
        spentBudget: 148000,
        billingMethod: 'CPM',
        cpmRate: 120,
        targetGeography: 'Bengaluru, Mumbai, Delhi NCR',
        targetCategory: 'Beverages & Site Refreshments',
        creativeUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=1200&auto=format&fit=crop&q=80',
        headline: 'Chilled Refreshments for Worksite Crew Delivered in 15 Minutes!',
        ctaText: 'Order Chilled Pack',
        priorityScore: 95,
        status: 'LIVE',
        approvalWorkflow: {
          createdBy: 'Siddharth Varma (Marketing Admin)',
          createdAt: '2026-07-28 10:00 AM',
          managerReviewedBy: 'Vikramaditya Rao (Super Admin)',
          financeApprovedBy: 'Deepak Mehrotra (Finance Admin)',
          superAdminApprovedBy: 'Vikramaditya Rao (Super Admin)',
          currentStage: 'LIVE',
        },
        analytics: {
          impressions: 1233333,
          clicks: 49333,
          ctrPercent: 4.0,
          productViews: 38200,
          addToCarts: 18400,
          attributableOrders: 14200,
          attributableRevenue: 947200,
          roasMultiplier: 6.4,
        },
      },
      {
        id: 'ad-bosch-02',
        campaignName: 'Bosch Heavy Duty Rotary Hammers & Impact Drills',
        advertiserBrand: 'Bosch Power Tools India',
        brandContactEmail: 'retailmedia@bosch-pt.co.in',
        placement: 'SEARCH_TOP_SPONSORED',
        startDate: '2026-08-10',
        endDate: '2026-09-15',
        totalBudget: 500000,
        spentBudget: 210000,
        billingMethod: 'CPC',
        cpcRate: 14,
        targetGeography: 'Pan-India All Hubs',
        targetCategory: 'Power Tools & Machinery',
        creativeUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=1200&auto=format&fit=crop&q=80',
        headline: 'Bosch Professional Cordless Impact Drills with 3-Year Warranty',
        ctaText: 'Explore Pro Range',
        priorityScore: 90,
        status: 'LIVE',
        approvalWorkflow: {
          createdBy: 'Siddharth Varma (Marketing Admin)',
          createdAt: '2026-08-05 02:30 PM',
          managerReviewedBy: 'Pooja Narang (Operations Admin)',
          financeApprovedBy: 'Deepak Mehrotra (Finance Admin)',
          superAdminApprovedBy: 'Vikramaditya Rao (Super Admin)',
          currentStage: 'LIVE',
        },
        analytics: {
          impressions: 650000,
          clicks: 15000,
          ctrPercent: 2.3,
          productViews: 14200,
          addToCarts: 6800,
          attributableOrders: 5100,
          attributableRevenue: 1836000,
          roasMultiplier: 8.7,
        },
      },
      {
        id: 'ad-schneider-03',
        campaignName: 'Schneider Electric Acti9 Industrial MCB Launch',
        advertiserBrand: 'Schneider Electric',
        brandContactEmail: 'promotions@schneider-electric.co.in',
        placement: 'PRODUCT_LIST_SPONSORED',
        startDate: '2026-08-20',
        endDate: '2026-09-30',
        totalBudget: 350000,
        spentBudget: 4500,
        billingMethod: 'CPM',
        cpmRate: 150,
        targetGeography: 'Mumbai & MMR, Pune, Ahmedabad',
        targetCategory: 'Electrical Switchgears',
        creativeUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&auto=format&fit=crop&q=80',
        headline: 'Schneider Electric Acti9 Dual-Safety Circuit Breakers',
        ctaText: 'Buy Authorized Stock',
        priorityScore: 88,
        status: 'PENDING_APPROVAL',
        approvalWorkflow: {
          createdBy: 'Siddharth Varma (Marketing Admin)',
          createdAt: '2026-08-24 11:15 AM',
          currentStage: 'FINANCE_REVIEW',
        },
        analytics: {
          impressions: 30000,
          clicks: 900,
          ctrPercent: 3.0,
          productViews: 750,
          addToCarts: 310,
          attributableOrders: 210,
          attributableRevenue: 145000,
          roasMultiplier: 32.2,
        },
      },
    ];

    // 6. CMS Banners & Collections
    this.cmsBanners = [
      {
        id: 'cms-ban-01',
        title: 'Emergency Job-Site Supplies Delivered in 15 Minutes',
        subtitle: '100% Genuine GST ITC Invoices Guaranteed across 10 Metropolitan Hubs',
        imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=1200&auto=format&fit=crop&q=80',
        targetScreen: 'HOME_EXPLORE',
        cityScope: 'all',
        priority: 1,
        isActive: true,
        validUntil: '2026-12-31',
      },
      {
        id: 'cms-ban-02',
        title: 'Monsoon Heavy Plumbing & Dewatering Pumps Sale',
        subtitle: 'Up to 25% Off on Crompton Kirloskar Submersible Pumps',
        imageUrl: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=1200&auto=format&fit=crop&q=80',
        targetScreen: 'CATEGORY_PLUMBING',
        cityScope: 'bengaluru',
        priority: 2,
        isActive: true,
        validUntil: '2026-09-15',
      },
    ];

    this.cmsCollections = [
      {
        id: 'col-trending',
        title: 'Trending Heavy Switchgears & Cables',
        slug: 'trending-switchgears',
        bannerBgColor: 'bg-emerald-900',
        productIds: ['prod-01', 'prod-03'],
        cityScope: 'all',
        isActive: true,
      },
      {
        id: 'col-best-sellers',
        title: 'Contractor Daily Best Sellers',
        slug: 'contractor-bestsellers',
        bannerBgColor: 'bg-blue-900',
        productIds: ['prod-02', 'prod-04'],
        cityScope: 'all',
        isActive: true,
      },
    ];

    // 7. Employee User Directory & Dynamic Roles
    this.employees = [
      {
        id: 'emp-001',
        employeeCode: 'EMP-1001',
        name: 'Vikramaditya Rao',
        email: 'vikram.rao@qcom.trade',
        phone: '+91 98450 99881',
        designation: 'Chief Technology & Operations Officer',
        role: 'SUPER_ADMIN',
        roleTitle: 'Main Admin / Super Admin',
        department: 'Executive Leadership',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
        assignedRoleIds: ['role-super-admin'],
        status: 'ACTIVE',
        joiningDate: '2025-01-01',
        lastLogin: 'Just now',
        createdAt: '2025-01-01',
        mfaEnabled: true,
      },
      {
        id: 'emp-002',
        employeeCode: 'EMP-1002',
        name: 'Pooja Narang',
        email: 'pooja.n@qcom.trade',
        phone: '+91 98110 44552',
        designation: 'Senior Operations Lead (Bengaluru)',
        role: 'OPERATIONS_MANAGER',
        roleTitle: 'Operations Manager',
        department: 'Live Dispatch Operations',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
        assignedRoleIds: ['role-ops-mgr'],
        status: 'ACTIVE',
        joiningDate: '2025-02-15',
        lastLogin: '10 mins ago',
        createdAt: '2025-02-15',
        mfaEnabled: false,
      },
      {
        id: 'emp-003',
        employeeCode: 'EMP-1003',
        name: 'Anand Sundaram',
        email: 'anand.s@qcom.trade',
        phone: '+91 98200 33441',
        designation: 'Head of Hardware Partner Acquisition',
        role: 'SELLER_MANAGER',
        roleTitle: 'Seller Manager',
        department: 'Merchant Network',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
        assignedRoleIds: ['role-seller-mgr'],
        status: 'ACTIVE',
        joiningDate: '2025-03-10',
        lastLogin: '45 mins ago',
        createdAt: '2025-03-10',
        mfaEnabled: false,
      },
      {
        id: 'emp-004',
        employeeCode: 'EMP-1004',
        name: 'Kavita Hegde',
        email: 'kavita.h@qcom.trade',
        phone: '+91 98490 88771',
        designation: 'Fleet Logistics Director',
        role: 'DELIVERY_MANAGER',
        roleTitle: 'Rider / Delivery Manager',
        department: 'Fleet & Dispatch Logistics',
        avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
        assignedRoleIds: ['role-rider-mgr'],
        status: 'ACTIVE',
        joiningDate: '2025-03-20',
        lastLogin: '1 hour ago',
        createdAt: '2025-03-20',
        mfaEnabled: false,
      },
      {
        id: 'emp-005',
        employeeCode: 'EMP-1005',
        name: 'Deepak Mehrotra',
        email: 'deepak.m@qcom.trade',
        phone: '+91 98210 55662',
        designation: 'Head of Marketplace Treasury & GST',
        role: 'FINANCE_ADMIN',
        roleTitle: 'Finance Manager',
        department: 'Finance & Compliance',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
        assignedRoleIds: ['role-finance-mgr'],
        status: 'ACTIVE',
        joiningDate: '2025-02-01',
        lastLogin: 'Yesterday',
        createdAt: '2025-02-01',
        mfaEnabled: true,
      },
      {
        id: 'emp-006',
        employeeCode: 'EMP-1006',
        name: 'Nisha Pillai',
        email: 'nisha.p@qcom.trade',
        phone: '+91 98400 11223',
        designation: 'Senior Contractor Support Specialist',
        role: 'CUSTOMER_SUPPORT',
        roleTitle: 'Customer Support Executive',
        department: 'Contractor Care',
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
        assignedRoleIds: ['role-support-exec'],
        status: 'ACTIVE',
        joiningDate: '2025-04-12',
        lastLogin: 'Today 09:30 AM',
        createdAt: '2025-04-12',
        mfaEnabled: false,
      },
      {
        id: 'emp-008',
        employeeCode: 'EMP-1008',
        name: 'Siddharth Varma',
        email: 'siddharth.v@qcom.trade',
        phone: '+91 98190 77661',
        designation: 'Head of Growth & Retail Media Monetization',
        role: 'MARKETING_ADMIN',
        roleTitle: 'Marketing Manager',
        department: 'Brand Marketing & Growth',
        avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80',
        assignedRoleIds: ['role-marketing-mgr'],
        status: 'ACTIVE',
        joiningDate: '2025-05-01',
        lastLogin: 'Just now',
        createdAt: '2025-05-01',
        mfaEnabled: false,
      },
    ];
  }

  // Audit logger helper
  public logAudit(entry: Omit<AuditLogEntry, 'id' | 'timestamp'>) {
    const newEntry: AuditLogEntry = {
      ...entry,
      id: `aud-${Date.now().toString(36)}-${Math.random().toString(36).substring(2, 6)}`,
      timestamp: new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: true }) + ', Today',
    };
    this.auditLogs.unshift(newEntry);
  }

  // Dynamic Role Management Store Methods
  public getRoles(): AdminRoleDefinition[] {
    return this.dynamicRoles;
  }

  public getRoleById(roleId: string): AdminRoleDefinition | undefined {
    return this.dynamicRoles.find((r) => r.id === roleId || r.code === roleId);
  }

  public createRole(roleData: Omit<AdminRoleDefinition, 'id' | 'createdAt' | 'updatedAt'>): AdminRoleDefinition {
    const id = `role-${Date.now().toString(36)}-${Math.random().toString(36).substring(2, 5)}`;
    const newRole: AdminRoleDefinition = {
      ...roleData,
      id,
      code: roleData.code ? roleData.code.toUpperCase().replace(/\s+/g, '_') : id.toUpperCase(),
      status: roleData.status || 'ACTIVE',
      isSystemRole: false,
      createdAt: new Date().toISOString().split('T')[0],
      updatedAt: new Date().toISOString().split('T')[0],
    };

    this.dynamicRoles.push(newRole);
    this.logAudit({
      actorName: 'Main Admin',
      actorRole: 'SUPER_ADMIN',
      actionType: 'ROLE_CREATED',
      targetModule: 'RBAC Security',
      summary: `Created dynamic role "${newRole.name}" (${newRole.code}) with ${newRole.permissions.length} action permissions.`,
      severity: 'HIGH',
    });
    return newRole;
  }

  public updateRole(roleId: string, roleData: Partial<AdminRoleDefinition>): AdminRoleDefinition | null {
    const roleIndex = this.dynamicRoles.findIndex((r) => r.id === roleId || r.code === roleId);
    if (roleIndex === -1) return null;

    const existingRole = this.dynamicRoles[roleIndex];
    const updatedRole: AdminRoleDefinition = {
      ...existingRole,
      ...roleData,
      updatedAt: new Date().toISOString().split('T')[0],
    };

    this.dynamicRoles[roleIndex] = updatedRole;
    this.logAudit({
      actorName: 'Main Admin',
      actorRole: 'SUPER_ADMIN',
      actionType: 'ROLE_UPDATED',
      targetModule: 'RBAC Security',
      summary: `Updated role permissions for "${updatedRole.name}" (${updatedRole.code}). Assigned permissions: ${updatedRole.permissions.length}.`,
      severity: 'HIGH',
    });
    return updatedRole;
  }

  public deactivateRole(roleId: string): { success: boolean; affectedEmployeesCount: number; role?: AdminRoleDefinition; message?: string } {
    const role = this.getRoleById(roleId);
    if (!role) return { success: false, affectedEmployeesCount: 0, message: 'Role not found' };

    if (role.isSystemRole && role.code === 'SUPER_ADMIN') {
      return { success: false, affectedEmployeesCount: 0, message: 'System Super Admin role cannot be deactivated.' };
    }

    const affectedEmployees = this.employees.filter(
      (e) => e.status === 'ACTIVE' && (e.assignedRoleIds?.includes(role.id) || e.assignedRoleIds?.includes(role.code) || e.role === role.code)
    );

    role.status = 'INACTIVE';
    role.updatedAt = new Date().toISOString().split('T')[0];

    this.logAudit({
      actorName: 'Main Admin',
      actorRole: 'SUPER_ADMIN',
      actionType: 'ROLE_DEACTIVATED',
      targetModule: 'RBAC Security',
      summary: `Deactivated role "${role.name}". Warning: ${affectedEmployees.length} active employee(s) lost access derived from this role.`,
      severity: 'CRITICAL',
    });

    return {
      success: true,
      affectedEmployeesCount: affectedEmployees.length,
      role,
      message: `Role ${role.name} deactivated. ${affectedEmployees.length} employee(s) affected.`,
    };
  }

  // Employee Directory & Dynamic Multi-Role Management Methods
  public getEmployees(): AdminEmployeeUser[] {
    return this.employees;
  }

  public getEmployeeById(id: string): AdminEmployeeUser | undefined {
    return this.employees.find((e) => e.id === id || e.employeeCode === id);
  }

  public createEmployee(empData: Partial<AdminEmployeeUser>): AdminEmployeeUser {
    const id = `emp-${Date.now().toString(36)}`;
    const employeeCode = `EMP-${1000 + this.employees.length + 1}`;
    const assignedRoleIds = empData.assignedRoleIds && empData.assignedRoleIds.length > 0 ? empData.assignedRoleIds : ['role-order-ops-exec'];
    const primaryRoleDef = this.dynamicRoles.find((r) => assignedRoleIds.includes(r.id) || assignedRoleIds.includes(r.code)) || this.dynamicRoles[0];

    const newEmp: AdminEmployeeUser = {
      id,
      employeeCode,
      name: empData.name || 'New Staff Member',
      email: empData.email || `${employeeCode.toLowerCase()}@qcom.trade`,
      phone: empData.phone || '+91 99000 00000',
      designation: empData.designation || primaryRoleDef.name,
      role: primaryRoleDef.code,
      roleTitle: empData.roleTitle || primaryRoleDef.name,
      department: empData.department || primaryRoleDef.department,
      avatar: empData.avatar || 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
      assignedRoleIds,
      status: empData.status || 'ACTIVE',
      joiningDate: empData.joiningDate || new Date().toISOString().split('T')[0],
      lastLogin: 'Never',
      createdAt: new Date().toISOString().split('T')[0],
      mfaEnabled: false,
    };

    this.employees.push(newEmp);
    this.logAudit({
      actorName: 'Main Admin',
      actorRole: 'SUPER_ADMIN',
      actionType: 'EMPLOYEE_CREATED',
      targetModule: 'Employee Directory',
      summary: `Created new employee "${newEmp.name}" (${newEmp.employeeCode}). Roles assigned: ${assignedRoleIds.length}.`,
      severity: 'HIGH',
    });
    return newEmp;
  }

  public updateEmployee(id: string, empData: Partial<AdminEmployeeUser>): AdminEmployeeUser | null {
    const idx = this.employees.findIndex((e) => e.id === id);
    if (idx === -1) return null;

    const existing = this.employees[idx];
    const updated = { ...existing, ...empData };

    if (empData.assignedRoleIds && empData.assignedRoleIds.length > 0) {
      const primaryRoleDef = this.dynamicRoles.find((r) => empData.assignedRoleIds!.includes(r.id) || empData.assignedRoleIds!.includes(r.code));
      if (primaryRoleDef) {
        updated.role = primaryRoleDef.code;
        updated.roleTitle = primaryRoleDef.name;
      }
    }

    this.employees[idx] = updated;
    this.logAudit({
      actorName: 'Main Admin',
      actorRole: 'SUPER_ADMIN',
      actionType: 'EMPLOYEE_UPDATED',
      targetModule: 'Employee Directory',
      summary: `Updated details & roles for employee "${updated.name}" (${updated.employeeCode}).`,
      severity: 'MEDIUM',
    });
    return updated;
  }

  public setEmployeeStatus(id: string, status: 'ACTIVE' | 'INACTIVE' | 'SUSPENDED', reason?: string): AdminEmployeeUser | null {
    const emp = this.getEmployeeById(id);
    if (!emp) return null;

    const prevStatus = emp.status;
    emp.status = status;

    this.logAudit({
      actorName: 'Main Admin',
      actorRole: 'SUPER_ADMIN',
      actionType: status === 'SUSPENDED' ? 'EMPLOYEE_SUSPENDED' : status === 'INACTIVE' ? 'EMPLOYEE_DEACTIVATED' : 'EMPLOYEE_ACTIVATED',
      targetModule: 'Employee Directory',
      summary: `Changed employee "${emp.name}" status from ${prevStatus} to ${status}. Justification: ${reason || 'Administrative action'}.`,
      severity: status === 'SUSPENDED' ? 'CRITICAL' : 'HIGH',
    });
    return emp;
  }

  public deleteEmployee(id: string): { success: boolean; message: string } {
    const idx = this.employees.findIndex((e) => e.id === id || e.employeeCode === id);
    if (idx === -1) {
      return { success: false, message: 'Employee not found.' };
    }

    const emp = this.employees[idx];
    if (emp.role === 'SUPER_ADMIN' || emp.id === 'emp-001') {
      return { success: false, message: 'Primary Super Admin account cannot be deleted.' };
    }

    this.employees.splice(idx, 1);
    this.logAudit({
      actorName: 'Main Admin',
      actorRole: 'SUPER_ADMIN',
      actionType: 'EMPLOYEE_DELETED',
      targetModule: 'Employee Directory',
      summary: `Permanently deleted employee record for "${emp.name}" (${emp.employeeCode}).`,
      severity: 'CRITICAL',
    });

    return { success: true, message: `Employee "${emp.name}" (${emp.employeeCode}) deleted successfully.` };
  }

  public deleteRole(roleId: string): { success: boolean; message: string } {
    const idx = this.dynamicRoles.findIndex((r) => r.id === roleId || r.code === roleId);
    if (idx === -1) {
      return { success: false, message: 'Role not found.' };
    }

    const role = this.dynamicRoles[idx];
    if (role.isSystemRole || role.code === 'SUPER_ADMIN') {
      return { success: false, message: 'System Super Admin role cannot be deleted.' };
    }

    this.dynamicRoles.splice(idx, 1);
    this.logAudit({
      actorName: 'Main Admin',
      actorRole: 'SUPER_ADMIN',
      actionType: 'ROLE_DELETED',
      targetModule: 'RBAC Security',
      summary: `Permanently deleted dynamic role "${role.name}" (${role.code}).`,
      severity: 'CRITICAL',
    });

    return { success: true, message: `Dynamic role "${role.name}" deleted successfully.` };
  }

}

export const authoritativeAdminStore = new AdminStore();
