import { AdminRole, AdminPermission, AdminUser } from '../src/types/admin';

export const ROLE_PERMISSIONS: Record<AdminRole, AdminPermission[]> = {
  SUPER_ADMIN: [
    'dashboard.view',
    'orders.view',
    'orders.edit_status',
    'orders.cancel',
    'orders.assign_rider',
    'sellers.view',
    'sellers.approve',
    'sellers.suspend',
    'sellers.edit_commission',
    'riders.view',
    'riders.approve',
    'riders.suspend',
    'riders.broadcast',
    'customers.view',
    'customers.edit_status',
    'customers.view_sensitive',
    'inventory.view',
    'inventory.edit_stock',
    'inventory.edit_price',
    'payments.view',
    'payments.reconcile',
    'refunds.view',
    'refunds.create',
    'refunds.approve',
    'settlements.view',
    'settlements.process',
    'pricing.view',
    'pricing.manage',
    'service_areas.view',
    'service_areas.manage',
    'audit.view',
    'support.view',
    'support.manage',
    'settings.manage',
  ],

  OPERATIONS_ADMIN: [
    'dashboard.view',
    'orders.view',
    'orders.edit_status',
    'orders.cancel',
    'orders.assign_rider',
    'sellers.view',
    'sellers.suspend',
    'riders.view',
    'riders.approve',
    'riders.suspend',
    'riders.broadcast',
    'customers.view',
    'inventory.view',
    'inventory.edit_stock',
    'service_areas.view',
    'service_areas.manage',
    'support.view',
    'support.manage',
    'audit.view',
  ],

  SELLER_MANAGER: [
    'dashboard.view',
    'sellers.view',
    'sellers.approve',
    'sellers.suspend',
    'sellers.edit_commission',
    'inventory.view',
    'inventory.edit_price',
    'pricing.view',
    'orders.view',
    'audit.view',
  ],

  DELIVERY_MANAGER: [
    'dashboard.view',
    'riders.view',
    'riders.approve',
    'riders.suspend',
    'riders.broadcast',
    'orders.view',
    'orders.assign_rider',
    'service_areas.view',
    'audit.view',
  ],

  FINANCE_ADMIN: [
    'dashboard.view',
    'orders.view',
    'sellers.view',
    'payments.view',
    'payments.reconcile',
    'refunds.view',
    'refunds.create',
    'refunds.approve',
    'settlements.view',
    'settlements.process',
    'pricing.view',
    'pricing.manage',
    'audit.view',
  ],

  CUSTOMER_SUPPORT: [
    'dashboard.view',
    'customers.view',
    'customers.edit_status',
    'orders.view',
    'orders.cancel',
    'refunds.view',
    'refunds.create',
    'support.view',
    'support.manage',
  ],

  ANALYST: [
    'dashboard.view',
    'orders.view',
    'sellers.view',
    'riders.view',
    'customers.view',
    'inventory.view',
    'payments.view',
    'refunds.view',
    'settlements.view',
    'service_areas.view',
    'pricing.view',
    'audit.view',
  ],
};

export const PRESET_ADMIN_USERS: AdminUser[] = [
  {
    id: 'adm-001',
    name: 'Vikramaditya Rao',
    email: 'vikram.rao@qcom.trade',
    role: 'SUPER_ADMIN',
    roleTitle: 'Chief Technology & Operations Officer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    department: 'Executive Management',
    lastLogin: 'Today, 08:30 AM',
  },
  {
    id: 'adm-002',
    name: 'Pooja Narang',
    email: 'pooja.n@qcom.trade',
    role: 'OPERATIONS_ADMIN',
    roleTitle: 'Senior Operations Lead (Bengaluru)',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    department: 'Live Dispatch Operations',
    lastLogin: 'Today, 09:12 AM',
  },
  {
    id: 'adm-003',
    name: 'Anand Sundaram',
    email: 'anand.s@qcom.trade',
    role: 'SELLER_MANAGER',
    roleTitle: 'Head of Hardware Partner Acquisition',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    department: 'Merchant Network',
    lastLogin: 'Today, 07:45 AM',
  },
  {
    id: 'adm-004',
    name: 'Kavita Hegde',
    email: 'kavita.h@qcom.trade',
    role: 'DELIVERY_MANAGER',
    roleTitle: 'Fleet Logistics Director',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
    department: 'Rider Operations & SLA',
    lastLogin: 'Today, 08:00 AM',
  },
  {
    id: 'adm-005',
    name: 'Deepak Mehrotra',
    email: 'deepak.m@qcom.trade',
    role: 'FINANCE_ADMIN',
    roleTitle: 'Head of Marketplace Treasury & GST',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
    department: 'Finance & Compliance',
    lastLogin: 'Yesterday, 06:20 PM',
  },
  {
    id: 'adm-006',
    name: 'Nisha Pillai',
    email: 'nisha.p@qcom.trade',
    role: 'CUSTOMER_SUPPORT',
    roleTitle: 'Senior Contractor Support Specialist',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
    department: 'Contractor Care',
    lastLogin: 'Today, 09:30 AM',
  },
  {
    id: 'adm-007',
    name: 'Rohan Deshmukh',
    email: 'rohan.d@qcom.trade',
    role: 'ANALYST',
    roleTitle: 'Growth & Efficiency Data Analyst',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
    department: 'Business Intelligence',
    lastLogin: 'Today, 06:15 AM',
  },
];

export function hasPermission(role: AdminRole, permission: AdminPermission): boolean {
  const allowed = ROLE_PERMISSIONS[role] || [];
  return allowed.includes(permission);
}
